#!/usr/bin/env python3
"""
Generate VHAL_PROPERTIES entries for ailog's knowledge pack from an AOSP tree.

The authoritative list of vehicle properties — names, access mode, change mode,
and required permission — lives in VehicleProperty.aidl (and its javadoc) inside
an AOSP checkout. This tool parses that file and prints ready-to-paste Python
dict entries for src/ailog/knowledge_pack.py, so the pack can be grown from
verified source instead of hand-written facts.

Usage:
    python3 tools/gen_vhal_knowledge.py <path-to-VehicleProperty.aidl>

Typical location in an AOSP tree:
    hardware/interfaces/automotive/vehicle/aidl/android/hardware/automotive/vehicle/VehicleProperty.aidl

Review the output before committing — a generated fact is only as good as the
source comment, and some properties are better described by hand.
"""

import re
import sys

# One enum member with its preceding /** ... */ javadoc block.
_MEMBER = re.compile(
    r'/\*\*(?P<doc>.*?)\*/\s*(?P<name>[A-Z][A-Z0-9_]+)\s*=',
    re.DOTALL,
)
_ACCESS = re.compile(r'@access\s+VehiclePropertyAccess\.(\w+)')
_CHANGE = re.compile(r'@change_mode\s+VehiclePropertyChangeMode\.(\w+)')
# Permission is written a few ways across AOSP versions.
_PERM = re.compile(r'(Car\.PERMISSION_[A-Z_]+|android\.car\.permission\.[A-Z_]+)')


def _first_sentence(doc):
    """Extract the first prose sentence from a javadoc block."""
    text = []
    for raw in doc.splitlines():
        line = raw.strip().lstrip('*').strip()
        if not line or line.startswith('@'):
            if text:
                break
            continue
        text.append(line)
        if line.endswith('.'):
            break
    joined = ' '.join(text).strip()
    # Cut at the first sentence boundary.
    m = re.search(r'(.+?\.)(\s|$)', joined)
    return (m.group(1) if m else joined)[:200]


def parse(source):
    """Yield (name, access, change_mode, permission, summary) tuples."""
    for m in _MEMBER.finditer(source):
        name = m.group('name')
        doc = m.group('doc')
        # Skip enum housekeeping members.
        if name in ('INVALID',) or name.startswith('MASK') or name.startswith('SHIFT'):
            continue
        access = (_ACCESS.search(doc) or [None, ''])[1] if _ACCESS.search(doc) else ''
        change = (_CHANGE.search(doc) or [None, ''])[1] if _CHANGE.search(doc) else ''
        perm_m = _PERM.search(doc)
        perm = perm_m.group(1) if perm_m else ''
        yield name, access, change, perm, _first_sentence(doc)


def to_entry(name, access, change, perm, summary):
    """Format one VHAL_PROPERTIES dict entry as Python source."""
    short = summary[:60].rstrip('.') or name
    parts = [summary] if summary else [f'{name} vehicle property.']
    if access:
        parts.append(f'Access: {access}.')
    if change:
        parts.append(f'Change mode: {change}.')
    if perm:
        parts.append(f'Requires {perm}.')
    guidance = ' '.join(parts)
    return f"    {name!r}: ({short!r},\n        {guidance!r}),"


def main(argv):
    if len(argv) != 2:
        print(__doc__)
        return 2
    try:
        with open(argv[1], encoding='utf-8', errors='replace') as f:
            source = f.read()
    except OSError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1

    count = 0
    print("# Generated by tools/gen_vhal_knowledge.py — review before committing.")
    for row in parse(source):
        print(to_entry(*row))
        count += 1
    print(f"# {count} properties parsed.", file=sys.stderr)
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
